#!/usr/bin/env node
// build_i18n.mjs — bundle the per-locale JSON catalogues under web/i18n/ into
// the single synchronously-loadable web/i18n/locales.js consumed by the runtime
// (web/i18n.js). Run via `make i18n`. Authoring stays in the JSON files; this
// generated bundle is committed like the vendored Monaco/xterm assets.
//
// Usage: node scripts/build_i18n.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const i18nDir = join(here, "..", "web", "i18n");
const outPath = join(i18nDir, "locales.js");

// Discover every <locale>.json in web/i18n (en, fr, es, de, …), parse it, and
// fail loudly on malformed JSON so a typo can't silently ship an empty locale.
const catalogs = {};
const files = readdirSync(i18nDir)
  .filter((f) => f.endsWith(".json"))
  .sort();
let totalKeys = 0;
for (const f of files) {
  const id = f.replace(/\.json$/, "");
  let data;
  try {
    data = JSON.parse(readFileSync(join(i18nDir, f), "utf8"));
  } catch (e) {
    console.error(`build_i18n: failed to parse web/i18n/${f}: ${e.message}`);
    process.exit(1);
  }
  catalogs[id] = data;
  totalKeys += Object.keys(data).length;
}

if (!catalogs.en) {
  console.error("build_i18n: web/i18n/en.json is required (base/fallback locale)");
  process.exit(1);
}

// Warn (don't fail) when a non-base locale is missing keys the base has — the
// runtime falls back to English, but a coverage gap is worth surfacing.
const enKeys = Object.keys(catalogs.en);
for (const id of Object.keys(catalogs)) {
  if (id === "en") continue;
  const missing = enKeys.filter((k) => !(k in catalogs[id]));
  if (missing.length) {
    console.warn(`build_i18n: ${id}.json is missing ${missing.length} key(s) present in en.json (will fall back to English)`);
  }
}

const banner =
  "// AUTO-GENERATED by `make i18n` (scripts/build_i18n.mjs) from\n" +
  "// web/i18n/<locale>.json — do not edit by hand. Sets window.OMNIS_I18N,\n" +
  "// the catalogue bundle read synchronously by web/i18n.js.\n";
const body = "window.OMNIS_I18N = " + JSON.stringify(catalogs, null, 0) + ";\n";
writeFileSync(outPath, banner + body, "utf8");

console.log(`build_i18n: wrote web/i18n/locales.js (${files.length} locales, ${totalKeys} total keys)`);
